[package]
name = "memg"
version = "1.0.0"
authors = ["DevHyperCoder <arduinoleo88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
structopt = "0.3.22"
